function [fitresult, gof] = createFit(x, p)
%CREATEFIT(X,P11)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: p11
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-May-2017 23:19:47


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, p);
ft = fittype( 'a*exp(-b*x)+c', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.48471897496528 0.507070565618313 0.269168762053444];
[fitresult, gof] = fit( xData, yData, ft, opts );




